version: "3.8"
services: 
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: 1qaz!QAZ
      POSTGRES_USER: ui_test
      POSTGRES_DB: ui_test
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./sql/create_users.sql:/docker-entrypoint-initdb.d/create_users.sql
    ports:
      - "5433:5432"
  web:
    image: node-server
    depends_on: 
      - db
    ports: 
      - "5000:5000"
      - "3000:3000"
      - "5001:5001"
    command: bash -c "cd /app && node server.js"
    